### ISSUE TITLE
top1000 for AAD Authentication methods - Password protection

### ISSUE THREAD

**Issue by ka2er** [tarraschk/richelieu#1]
Hi,

it would be great to have a top 1000 word designed for 0365 password protection (see https://www.lemagit.fr/actualites/252461051/Active-Directory-Microsoft-propose-une-couche-de-protection-additionnelle-pour-les-comptes).
Here is the description of the input field.

`A list of words, one per line, to prevent your users from using in their passwords. You should include words specific to your organization, such as your products, trademarks, industries, local cities and towns, and local sports teams. Your list can contain up to 1000 words. These are case insensitive, and common character substitutions (o for 0, etc) are automatically considered.
`
This is what I used to narrow the list but don't know if it's the most effective as I don't have counter attempt for each word...

`cat $HOME/Downloads/french_passwords_top5000.webarchive | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- | awk 'length($0)>3' | head -n 1000`

**Comment by tarraschk** [comment]
Done: https://github.com/tarraschk/richelieu/blob/master/french_passwords_top1000.txt

I just did:

```bash
head -n1000 french_passwords_top5000.txt > french_passwords_top1000.txt
```

Is it okay for you?

**Comment by ka2er** [comment]
Thanks you !

On 5 Jul 2019, at 23:54, Maxime Alay-Eddine <notifications@github.com<mailto:notifications@github.com>> wrote:


Done: https://github.com/tarraschk/richelieu/blob/master/french_passwords_top1000.txt

Is it okay for you?
